[build]
  command = "npm install"
  publish = "/"
  functions = "netlify/functions"

# For local development
[[dev]]
  command = "netlify dev"
  targetPort = 3000
  publish = "/"
  functions = "netlify/functions"

# For production
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true
